<?php

namespace App\Repositories\Eloquent;

use Illuminate\Support\Facades\Auth;
use Parsedown;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Contracts\Repositories\ReplyRepository;
use App\Models\Reply;
use App\Validators\ReplyValidator;

/**
 * Class ReplyRepositoryEloquent
 * @package namespace App\Repositories\Eloquent;
 */
class ReplyRepositoryEloquent extends BaseRepository implements ReplyRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Reply::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function create(array $attributes)
    {
        $attributes['user_id'] = Auth::id();
        $attributes['origin_body'] = $attributes['body'];
        //TODO markdown 做下封装处理
        $attributes['body'] = (new Parsedown())->setBreaksEnabled(true)->text($attributes['body']);

        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
