<?php

namespace App\Repositories\Eloquent;

use League\HTMLToMarkdown\HtmlConverter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Contracts\Repositories\TopicRepository;
use App\Models\Topic;

/**
 * Class TopicRepositoryEloquent
 * @package namespace App\Repositories\Eloquent;
 */
class TopicRepositoryEloquent extends BaseRepository implements TopicRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Topic::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function create(array $attributes)
    {
        if (isset($attributes['origin_body'])) {
            $converter = new HtmlConverter();
            $attributes['body'] = $converter->convert($attributes['origin_body']);
        }
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
